# Generated by Django 6.1.2 on 2026-10-08 14:31

import links.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applink',
            name='url',
            field=links.fields.IntranetURLField(),
        ),
    ]
