import {
  AppWindow,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  ClipboardList,
  Cloud,
  Coins,
  CreditCard,
  Database,
  FileText,
  Folder,
  Gavel,
  Globe,
  GraduationCap,
  Handshake,
  HeartPulse,
  Headset,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Lock,
  Mail,
  MessageSquare,
  PiggyBank,
  Receipt,
  Scale,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  TrendingUp,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

// Icon names admins can type into the "icon" field in the Django admin.
// To add one, import it from lucide-react (https://lucide.dev/icons) and add its kebab-case name here.
export const ICONS = {
  "app-window": AppWindow,
  banknote: Banknote,
  "bar-chart": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  calendar: Calendar,
  "clipboard-list": ClipboardList,
  cloud: Cloud,
  coins: Coins,
  "credit-card": CreditCard,
  dashboard: LayoutDashboard,
  database: Database,
  "file-text": FileText,
  folder: Folder,
  gavel: Gavel,
  globe: Globe,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  headset: Headset,
  "heart-pulse": HeartPulse,
  key: KeyRound,
  landmark: Landmark,
  "life-buoy": LifeBuoy,
  "line-chart": LineChart,
  lock: Lock,
  mail: Mail,
  message: MessageSquare,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  scale: Scale,
  server: Server,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  "trending-up": TrendingUp,
  users: Users,
  wallet: Wallet,
  wrench: Wrench,
};
